# Generated by Django 6.0.2 on 2026-02-21 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The question text', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('question_text', models.TextField(help_text='Detailed question description')),
                ('answer_text', models.TextField(help_text='Answer to the question')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status of the question', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this question should be featured prominently')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this question has been viewed')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search and organization', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for manual sorting within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='faq.faqcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faq_questions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faq_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ Question',
                'verbose_name_plural': 'FAQ Questions',
                'ordering': ['-is_featured', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment or suggestion')),
                ('is_helpful', models.BooleanField(blank=True, help_text='Whether the user found this answer helpful', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user (for anonymous feedback)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who provided feedback (can be anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='faq.faqquestion')),
            ],
            options={
                'verbose_name': 'FAQ Feedback',
                'verbose_name_plural': 'FAQ Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(help_text='The search query entered by user', max_length=200)),
                ('search_results_count', models.PositiveIntegerField(default=0, help_text='Number of results found')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ Search Log',
                'verbose_name_plural': 'FAQ Search Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='faqquestion',
            index=models.Index(fields=['status', 'is_featured'], name='faq_faqques_status_3485ab_idx'),
        ),
        migrations.AddIndex(
            model_name='faqquestion',
            index=models.Index(fields=['category', 'status'], name='faq_faqques_categor_e9d6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='faqquestion',
            index=models.Index(fields=['view_count'], name='faq_faqques_view_co_c3065c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faqfeedback',
            unique_together={('question', 'user')},
        ),
    ]
