# Generated by Django 6.0.2 on 2026-02-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_deleted_at_category_is_deleted_and_more'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='category',
            field=models.ForeignKey(help_text='Category this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='category.category'),
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
