# Generated by Django 6.0.2 on 2026-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faqquestion_category_delete_faqcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
    ]
