# Generated by Django 5.2.6 on 2026-03-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faqquestion_deleted_at_faqquestion_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this question was published', null=True),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this question is soft deleted'),
        ),
    ]
