# Generated by Django 5.2.6 on 2026-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_add_admin_interface_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this question is published and visible to users'),
        ),
    ]
