# Generated by Django 5.0 on 2026-01-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_district_alter_district_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state', 'name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['district', 'name']},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='district',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='state',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='city',
            new_name='district',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'district')},
        ),
    ]
