# Generated by Django 5.0 on 2026-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_city_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
        migrations.AddField(
            model_name='country',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
        migrations.AddField(
            model_name='district',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
        migrations.AddField(
            model_name='region',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
        migrations.AddField(
            model_name='state',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
    ]
