# Generated by Django 5.0 on 2026-02-07 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Karkahan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image for the user', null=True, upload_to='profile_images/')),
                ('factory', models.ForeignKey(help_text='The factory this user is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='Karkahan.factory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factory Profile',
                'verbose_name_plural': 'Factory Profiles',
            },
        ),
    ]
