# Generated by Django 5.0 on 2026-02-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_address_profile_date_of_birth_profile_gender_and_more'),
        ('Karkahan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='The factory this user is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='Karkahan.factory'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
