# Generated by Django 5.0 on 2026-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_profile_factory_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_app_notifications',
            field=models.BooleanField(default=True, help_text='Receive in-app notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', help_text='User role and permission level', max_length=20),
        ),
    ]
