# Generated by Django 6.0.2 on 2026-03-20 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_profile_created_at_alter_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address being rate limited')),
                ('action', models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset'), ('email_resend', 'Email Resend'), ('registration', 'Registration')], help_text='Type of action being rate limited', max_length=50)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of attempts in current window')),
                ('window_start', models.DateTimeField(help_text='Start time of current rate limiting window')),
                ('blocked_until', models.DateTimeField(blank=True, help_text='When the block expires (if currently blocked)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this rate limit entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this rate limit entry was last updated')),
            ],
            options={
                'verbose_name': 'Rate Limit',
                'verbose_name_plural': 'Rate Limits',
                'ordering': ['-updated_at'],
                'unique_together': {('ip_address', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username (even if user is deleted)', max_length=150)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_blocked', 'Login Blocked'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('email_verification_sent', 'Email Verification Sent'), ('email_verification_failed', 'Email Verification Failed'), ('profile_update', 'Profile Update'), ('registration', 'Registration'), ('logout', 'Logout')], help_text='Type of action performed', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the action was performed')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this activity was logged')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='Hashed version of the password', max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this password was set')),
                ('user', models.ForeignKey(help_text='User who changed password', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password History',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'password_hash')},
            },
        ),
    ]
