# Generated by Django 5.0 on 2026-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
    ]
