# Generated by Django 5.0 on 2026-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_category_blogpost_city_blogpost_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Mark as deleted without removing from database'),
        ),
    ]
