# Generated by Django 5.0 on 2026-02-05 18:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=blog.models.BlogImageUploadPath()),
        ),
    ]
