# Generated by Django 6.0.2 on 2026-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0002_factory_image_factoryimage'),
        ('blog', '0006_alter_blogimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_factories',
            field=models.ManyToManyField(blank=True, help_text='Factories related to this blog post', related_name='blog_posts', to='Karkahan.factory'),
        ),
    ]
