# Generated by Django 5.0 on 2026-02-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark as deleted without removing from database')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True)),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='home_videos/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted'], name='Home_homepa_is_dele_994a0e_idx'), models.Index(fields=['deleted_at'], name='Home_homepa_deleted_2e0c8d_idx'), models.Index(fields=['is_active'], name='Home_homepa_is_acti_b8b718_idx')],
            },
        ),
    ]
