# Generated by Django 5.2.6 on 2026-02-22 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark as deleted without removing from database')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read by admin')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who submitted this message (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at', '-is_read'],
                'indexes': [models.Index(fields=['is_deleted'], name='Home_contac_is_dele_97ec20_idx'), models.Index(fields=['deleted_at'], name='Home_contac_deleted_96b086_idx'), models.Index(fields=['is_read'], name='Home_contac_is_read_f4ac14_idx'), models.Index(fields=['email'], name='Home_contac_email_7e9c01_idx'), models.Index(fields=['created_at'], name='Home_contac_created_f16f45_idx'), models.Index(fields=['user'], name='Home_contac_user_id_757b89_idx')],
            },
        ),
    ]
