# Generated by Django 6.0.2 on 2026-03-12 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_contactmessage_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark as deleted without removing from database')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True)),
                ('subject', models.CharField(help_text='Subject of the reply email', max_length=200)),
                ('message', models.TextField(help_text='Content of the reply message')),
                ('recipient_email', models.EmailField(help_text='Email address the reply was sent to', max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the reply was sent')),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Status of the email sending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if email sending failed')),
            ],
            options={
                'verbose_name': 'Contact Reply',
                'verbose_name_plural': 'Contact Replies',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='has_replies',
            field=models.BooleanField(default=False, help_text='Whether this message has been replied to'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, help_text='When the last reply was sent', null=True),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['has_replies'], name='Home_contac_has_rep_25e5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['last_reply_at'], name='Home_contac_last_re_e11681_idx'),
        ),
        migrations.AddField(
            model_name='contactreply',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='The admin user who sent this reply', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactreply',
            name='contact_message',
            field=models.ForeignKey(help_text='The original contact message this reply is for', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Home.contactmessage'),
        ),
        migrations.AddIndex(
            model_name='contactreply',
            index=models.Index(fields=['is_deleted'], name='Home_contac_is_dele_c00386_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreply',
            index=models.Index(fields=['deleted_at'], name='Home_contac_deleted_970179_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreply',
            index=models.Index(fields=['contact_message'], name='Home_contac_contact_7ee691_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreply',
            index=models.Index(fields=['admin_user'], name='Home_contac_admin_u_a23209_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreply',
            index=models.Index(fields=['sent_at'], name='Home_contac_sent_at_43eeee_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreply',
            index=models.Index(fields=['email_status'], name='Home_contac_email_s_27dd08_idx'),
        ),
    ]
