# Generated by Django 5.2.6 on 2026-03-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_add_reply_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark as deleted without removing from database')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('page_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('refund', 'Refund Policy'), ('disclaimer', 'Disclaimer'), ('privacy', 'Privacy Policy'), ('about', 'About Us')], max_length=20, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_deleted'], name='Home_page_is_dele_acf936_idx'), models.Index(fields=['deleted_at'], name='Home_page_deleted_8d0f9c_idx'), models.Index(fields=['page_type'], name='Home_page_page_ty_67faf1_idx'), models.Index(fields=['is_published'], name='Home_page_is_publ_0af663_idx'), models.Index(fields=['slug'], name='Home_page_slug_95525b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark as deleted without removing from database')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Home.page')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_deleted'], name='Home_pagese_is_dele_7bf4f5_idx'), models.Index(fields=['deleted_at'], name='Home_pagese_deleted_591a42_idx'), models.Index(fields=['page'], name='Home_pagese_page_id_9dae28_idx'), models.Index(fields=['order'], name='Home_pagese_order_ab7719_idx')],
            },
        ),
    ]
