# Generated by Django 6.0.2 on 2026-03-29 17:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_page_pagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
