# Generated by Django 5.2.6 on 2026-03-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_page_content_alter_pagesection_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which pages appear in navigation'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['order'], name='Home_page_order_836acb_idx'),
        ),
    ]
