# Generated by Django 5.2.6 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='mobile_number',
            field=models.CharField(
                max_length=20, 
                blank=True, 
                help_text='Contact phone number (optional)'
            ),
        ),
    ]
