# Generated by Django 5.2.6 on 2026-01-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_category_deleted_at_category_is_deleted_and_more'),
        ('location', '0004_city_deleted_at_city_is_deleted_country_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark as deleted without removing from database')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft deleted', null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('factory_type', models.CharField(blank=True, help_text='e.g., Manufacturing, Assembly, Processing', max_length=100)),
                ('production_capacity', models.CharField(blank=True, help_text='e.g., 1000 units/month', max_length=200)),
                ('working_hours', models.CharField(blank=True, help_text='e.g., 9:00 AM - 6:00 PM', max_length=100)),
                ('holidays', models.TextField(blank=True, help_text='List of holidays observed')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='category.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='location.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='location.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='location.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='location.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='location.state')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='category.subcategory')),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factories',
                'ordering': ['name'],
            },
        ),
    ]
