# Generated by Django 5.0 on 2026-02-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='factories/'),
        ),
        migrations.CreateModel(
            name='FactoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='factories/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary image for the factory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Karkahan.factory')),
            ],
            options={
                'verbose_name': 'Factory Image',
                'verbose_name_plural': 'Factory Images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
