# Generated by Django 6.0.2 on 2026-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0002_factory_image_factoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste YouTube or Vimeo link here', null=True),
        ),
    ]
