# Generated by Django 6.0.2 on 2026-02-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0003_factory_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
    ]
