# Generated by Django 6.0.2 on 2026-02-16 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0004_factory_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this factory record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_factories', to=settings.AUTH_USER_MODEL),
        ),
    ]
