# Generated by Django 6.0.2 on 2026-02-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0005_factory_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price per unit', max_digits=10, null=True),
        ),
    ]
