# Generated by Django 6.0.2 on 2026-02-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0006_alter_factory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='image',
        ),
    ]
