# Generated by Django 6.0.2 on 2026-02-23 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0007_remove_factory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='Karkahan.factory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factory Purchase',
                'verbose_name_plural': 'Factory Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=200)),
                ('factory_slug', models.CharField(max_length=200)),
                ('factory_category', models.CharField(max_length=100)),
                ('factory_location', models.CharField(max_length=500)),
                ('factory_contact_person', models.CharField(blank=True, max_length=100)),
                ('factory_contact_phone', models.CharField(blank=True, max_length=20)),
                ('factory_contact_email', models.EmailField(blank=True, max_length=254)),
                ('factory_address', models.TextField(blank=True)),
                ('factory_website', models.URLField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_quantity', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateTimeField()),
                ('email_delivered', models.BooleanField(default=False)),
                ('email_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase History',
                'verbose_name_plural': 'Purchase History',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Karkahan.factory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping Cart Item',
                'verbose_name_plural': 'Shopping Cart Items',
                'unique_together': {('user', 'factory')},
            },
        ),
    ]
