# Generated by Django 6.0.2 on 2026-03-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0011_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one gateway can be active at a time')),
                ('key_id', models.CharField(blank=True, help_text='API Key ID (e.g., publishable key)', max_length=255)),
                ('key_secret', models.CharField(blank=True, help_text='API Secret Key', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook signing secret', max_length=255)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='e.g., card, upi, netbanking', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Gateway transaction ID', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Karkahan.paymentgateway'),
        ),
    ]
