# Generated by Django 5.2.6 on 2026-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0012_paymentgateway_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Auto-generated order number', max_length=50),
        ),
    ]
