# Generated by Django 5.2.6 on 2026-03-18 07:56

from django.db import migrations
from datetime import datetime
import django.db.models.deletion


def populate_order_numbers(apps, schema_editor):
    """Populate order_number field for existing orders"""
    Order = apps.get_model('Karkahan', 'Order')
    
    # Get all orders without order_number
    orders_without_number = Order.objects.filter(order_number='')
    
    for order in orders_without_number:
        # Generate order number in format: ORD-YYYY-MM-XXXX
        current_date = datetime.now()
        year = current_date.year
        month = current_date.month
        
        # Find the highest sequence number for this year-month
        last_order = Order.objects.filter(
            order_number__startswith=f"ORD-{year:04d}-{month:02d}-"
        ).order_by('-order_number').first()
        
        if last_order:
            # Extract the sequence number and increment
            sequence = int(last_order.order_number.split('-')[-1])
            new_sequence = sequence + 1
        else:
            # Start from 1 for this year-month
            new_sequence = 1
        
        order.order_number = f"ORD-{year:04d}-{month:02d}-{new_sequence:04d}"
        order.save()


def reverse_populate_order_numbers(apps, schema_editor):
    """Reverse operation - clear order_number field"""
    Order = apps.get_model('Karkahan', 'Order')
    Order.objects.update(order_number='')


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0013_order_order_number'),
    ]

    operations = [
        migrations.RunPython(
            populate_order_numbers,
            reverse_populate_order_numbers,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_number',)},
        ),
    ]
