# Generated by Django 5.2.6 on 2026-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0015_alter_order_unique_together_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry Needed')], default='pending', max_length=20),
        ),
    ]
