# Generated by Django 6.0.2 on 2026-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0016_add_email_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_email_error',
            field=models.TextField(blank=True, help_text='Last email error message for debugging', null=True),
        ),
    ]
