# Generated by Django 5.2.6 on 2026-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0017_order_last_email_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(default=False, help_text='Whether payment has been successfully completed and verified'),
        ),
    ]
