# Generated by Django 6.0.2 on 2026-03-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karkahan', '0018_add_payment_completed_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryViewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('today_views', models.PositiveIntegerField(default=0)),
                ('weekly_views', models.PositiveIntegerField(default=0)),
                ('monthly_views', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_stats', to='Karkahan.factory')),
            ],
            options={
                'verbose_name': 'Factory View Statistics',
                'verbose_name_plural': 'Factory View Statistics',
            },
        ),
        migrations.CreateModel(
            name='FactoryViewTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_trackers', to='Karkahan.factory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factory View Tracker',
                'verbose_name_plural': 'Factory View Trackers',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
