# Generated by Django 6.0.2 on 2026-02-13 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0001_initial'),
        ('category', '0002_category_deleted_at_category_is_deleted_and_more'),
        ('location', '0004_city_deleted_at_city_is_deleted_country_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='is_current_job',
        ),
        migrations.AddField(
            model_name='worker',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.country'),
        ),
        migrations.AddField(
            model_name='worker',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.region'),
        ),
        migrations.AddField(
            model_name='worker',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='category.subcategory'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='availability',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('C', 'Contract'), ('T', 'Temporary'), ('A', 'Available immediately')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='category.category'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.city'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='worker',
            name='expected_daily_wage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='skills',
            field=models.TextField(blank=True, help_text='List of skills and competencies'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.state'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
    ]
