# Generated by Django 6.0.2 on 2026-02-16 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0002_remove_worker_pincode_remove_worker_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this worker record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
