"""
Django settings for FactoryInfoHub project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import os
from pathlib import Path

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-development-key-not-for-production-use-this-is-very-weak-and-should-be-changed')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False')

# Allowed hosts configuration
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]

# Security settings for production
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if os.environ.get('SECURE_PROXY_SSL_HEADER', '').lower() == 'true' else None
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY')

# File Upload Settings - configurable via environment variables
# Default: 100MB for uploads, 1000 fields per request
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', 100 * 1024 * 1024))  # Default 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', 100 * 1024 * 1024))  # Default 100 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.environ.get('DATA_UPLOAD_MAX_NUMBER_FIELDS', 1000))  # Default 1000 fields


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'tinymce',
    'Home',
    'Accounts',
    'blog',
    'location',
    'category',
    'Karkahan',
    'Workers',
    'admin_interface',
    'faq',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

ROOT_URLCONF = 'FactoryInfoHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # your custom processor
                'Home.context_processors.global_pages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FactoryInfoHub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration with environment variable support
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # Use DATABASE_URL if provided (for PostgreSQL in production via URL)
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL)
    }
else:
    # PostgreSQL configuration using individual environment variables
    # Defaults to the server setup values if not specified
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'factoryhub'),
            'USER': os.environ.get('DB_USER', 'factoryhubuser'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'strongpassword'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,  # Persistent connections
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', 'prefer'),
            },
        }
    }

# Cache configuration with Redis support
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/1')
CACHE_REDIS_URL = os.environ.get('CACHE_REDIS_URL', REDIS_URL)

# Redis session configuration
SESSION_REDIS_HOST = os.environ.get('SESSION_REDIS_HOST', 'localhost')
SESSION_REDIS_PORT = int(os.environ.get('SESSION_REDIS_PORT', 6379))
SESSION_REDIS_DB = int(os.environ.get('SESSION_REDIS_DB', 1))
SESSION_REDIS_PASSWORD = os.environ.get('SESSION_REDIS_PASSWORD', None)

# Build Redis connection string for sessions
REDIS_SESSION_URL = f"redis://:{SESSION_REDIS_PASSWORD}@" if SESSION_REDIS_PASSWORD else "redis://"
REDIS_SESSION_URL += f"{SESSION_REDIS_HOST}:{SESSION_REDIS_PORT}/{SESSION_REDIS_DB}"

# Cache configuration - using database cache as fallback for compatibility
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
    }
}

# Try to use Redis cache if available, fallback to database cache
try:
    import django_redis
    CACHES['default'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CACHE_REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'factoryinfohub',
        'TIMEOUT': 300,
        'VERSION': 1,
    }
except ImportError:
    # Fallback to database cache if django-redis is not available
    pass

# Session configuration using database backend for better compatibility
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration (using GoDaddy SMTP Relay)
# Try to get email settings from environment variables first
import os
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'sg2nlvphout-v01.shr.prod.sin2.secureserver.net')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'

# Configure email backend with fallback
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Production email configuration
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    # Additional email settings for better reliability
    EMAIL_TIMEOUT = 30
    EMAIL_SSL_CERTFILE = None
    EMAIL_SSL_KEYFILE = None
else:
    # Development fallback - use console backend to see emails in terminal
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = ''
    EMAIL_PORT = 25
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    DEFAULT_FROM_EMAIL = 'noreply@factoryinfohub.com'

# Email backend configuration for fallback scenarios
EMAIL_FALLBACK_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# TinyMCE Configuration - Enhanced for Blog Editor
TINYMCE_DEFAULT_CONFIG = {
    'height': 600,
    'width': '100%',
    'menubar': True,
    'resize': True,
    'plugins': [
        'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview',
        'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
        'insertdatetime', 'media', 'table', 'paste', 'code', 'help', 'wordcount',
        'directionality', 'emoticons', 'pagebreak', 'nonbreaking', 'save',
        'toc', 'visualchars'
    ],
    'toolbar': [
        'undo redo | formatselect | bold italic backcolor | forecolor backcolor |',
        'alignleft aligncenter alignright alignjustify | bullist numlist outdent indent |',
        'removeformat | image media link | table | code | fullscreen | help',
        'ltr rtl | emoticons | pagebreak | nonbreaking | save'
    ],
    'toolbar_mode': 'sliding',
    'toolbar_sticky': True,
    'content_style': '''
        body { 
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; 
            font-size: 16px; 
            line-height: 1.8;
            color: #1e293b;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 { font-size: 2em; font-weight: 700; margin: 1.5em 0 0.5em; color: #1e293b; }
        h2 { font-size: 1.5em; font-weight: 600; margin: 1.2em 0 0.4em; color: #334155; }
        h3 { font-size: 1.25em; font-weight: 600; margin: 1em 0 0.3em; color: #475569; }
        p { margin: 0 0 1em; }
        ul, ol { padding-left: 2em; margin: 1em 0; }
        li { margin: 0.5em 0; }
        blockquote {
            border-left: 4px solid #EB662B;
            padding-left: 1em;
            margin: 1em 0;
            font-style: italic;
            color: #64748b;
        }
        code {
            background: #f1f5f9;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
        }
        pre {
            background: #1e293b;
            color: #e2e8f0;
            padding: 1em;
            border-radius: 8px;
            overflow-x: auto;
            margin: 1em 0;
        }
        pre code {
            background: none;
            padding: 0;
            color: inherit;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin: 1em 0;
        }
        th, td {
            border: 1px solid #e2e8f0;
            padding: 0.75em;
            text-align: left;
        }
        th {
            background: #f8fafc;
            font-weight: 600;
        }
        img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }
        .img-fluid { max-width: 100%; height: auto; }
        .img-thumbnail { border: 1px solid #dee2e6; padding: 4px; }
        .rounded { border-radius: 8px; }
        .rounded-circle { border-radius: 50%; }
        a { color: #EB662B; text-decoration: none; }
        a:hover { text-decoration: underline; }
        hr { border: none; border-top: 1px solid #e2e8f0; margin: 2em 0; }
    ''',
    'branding': False,
    'statusbar': True,
    'elementpath': True,
    'path_powered_by': False,
    
    # Image upload configuration
    'images_upload_url': '/blog/upload-image/',
    'images_upload_base_path': '/media/',
    'images_upload_credentials': True,
    'automatic_uploads': True,
    'file_picker_types': 'image',
    'images_reuse_filename': True,
    'image_advtab': True,
    'image_caption': True,
    'image_title': True,
    'image_description': True,
    'image_class_list': [
        {'title': 'None', 'value': ''},
        {'title': 'Responsive', 'value': 'img-fluid'},
        {'title': 'Thumbnail', 'value': 'img-thumbnail'},
        {'title': 'Rounded', 'value': 'rounded'},
        {'title': 'Circle', 'value': 'rounded-circle'},
        {'title': 'Full Width', 'value': 'img-full-width'},
    ],
    # Allowed image file types
    'images_file_types': 'jpg,jpeg,png,gif,webp,svg',
    # Image size limits
    'image_max_width': 1920,
    'image_max_height': 1080,
    'image_size_mode': 'constrain',
    'image_dimensions': True,
    
    # Link settings
    'link_default_target': '_blank',
    'link_default_protocol': 'https',
    'link_assume_external_targets': True,
    'link_list': [
        {'title': 'My page 1', 'value': 'https://www.example.com/page1'},
        {'title': 'My page 2', 'value': 'https://www.example.com/page2'},
    ],
    
    # Table settings
    'table_toolbar': 'tableprops tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol',
    'table_column_resizing': 'resizetable',
    'table_default_border': '1',
    'table_default_cellpadding': '10',
    
    # Format settings
    'format_nonbreaking_selector': 'td',
    'entity_encoding': 'raw',
    'valid_elements': '*[*]',
    'extended_valid_elements': 'iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder],script[src|type]',
    
    # Paste settings
    'paste_data_images': True,
    'paste_webkit_styles': 'all',
    'paste_merge_formats': True,
    'paste_remove_styles_if_webkit': False,
    
    # Save settings
    'save_enablewhendirty': True,
    'save_onsavecallback': None,
    
    # Directionality
    'directionality': 'ltr',
    
    # Language
    'language': 'en',
    
    # Content CSS (additional custom styles)
    'content_css': [
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css',
    ],
    
    # External styles
    'importcss_append': True,
    
    # Templates (optional - for reusable content blocks)
    'templates': [
        {'title': 'Call to Action', 'description': 'Call to action block', 'content': '<div class="cta-box" style="background: #f8fafc; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0;"><h3>Call to Action</h3><p>Your content here...</p></div>'},
        {'title': 'Info Box', 'description': 'Information box', 'content': '<div class="info-box" style="background: #eff6ff; border-left: 4px solid #3b82f6; padding: 15px; margin: 15px 0;"><p><strong>Info:</strong> Your information here...</p></div>'},
        {'title': 'Warning Box', 'description': 'Warning box', 'content': '<div class="warning-box" style="background: #fffbeb; border-left: 4px solid #f59e0b; padding: 15px; margin: 15px 0;"><p><strong>Warning:</strong> Your warning here...</p></div>'},
    ],
    
    # Style formats
    'style_formats': [
        {'title': 'Headings', 'items': [
            {'title': 'Heading 1', 'format': 'h1'},
            {'title': 'Heading 2', 'format': 'h2'},
            {'title': 'Heading 3', 'format': 'h3'},
            {'title': 'Heading 4', 'format': 'h4'},
        ]},
        {'title': 'Inline', 'items': [
            {'title': 'Bold', 'icon': 'bold', 'format': 'bold'},
            {'title': 'Italic', 'icon': 'italic', 'format': 'italic'},
            {'title': 'Underline', 'icon': 'underline', 'format': 'underline'},
            {'title': 'Strikethrough', 'icon': 'strikethrough', 'format': 'strikethrough'},
            {'title': 'Superscript', 'icon': 'superscript', 'format': 'superscript'},
            {'title': 'Subscript', 'icon': 'subscript', 'format': 'subscript'},
            {'title': 'Code', 'icon': 'code', 'format': 'code'},
        ]},
        {'title': 'Blocks', 'items': [
            {'title': 'Paragraph', 'format': 'p'},
            {'title': 'Blockquote', 'format': 'blockquote'},
            {'title': 'Div', 'format': 'div'},
            {'title': 'Pre', 'format': 'pre'},
        ]},
        {'title': 'Alignment', 'items': [
            {'title': 'Left', 'icon': 'alignleft', 'format': 'alignleft'},
            {'title': 'Center', 'icon': 'aligncenter', 'format': 'aligncenter'},
            {'title': 'Right', 'icon': 'alignright', 'format': 'alignright'},
            {'title': 'Justify', 'icon': 'alignjustify', 'format': 'alignjustify'},
        ]},
    ],
    
    # Custom colors
    'color_map': [
        'EB662B', 'Primary Orange',
        '1e293b', 'Dark Text',
        '64748b', 'Gray Text',
        '3b82f6', 'Blue',
        '10b981', 'Green',
        'ef4444', 'Red',
        'f59e0b', 'Amber',
        '8b5cf6', 'Purple',
        'ffffff', 'White',
        '000000', 'Black',
    ],
    
    # Font list
    'font_family_formats': 'Inter=inter, sans-serif; Arial=arial,helvetica,sans-serif; Georgia=georgia,times,times new roman,serif; Courier New=courier new,courier,monospace;',
    'font_size_formats': '10px 11px 12px 14px 16px 18px 24px 36px 48px',
    
    # Word count
    'wordcount_countregex': r'[\w\']+,[\w\']+',
    
    # Mobile settings
    'mobile': {
        'plugins': ['autolink', 'lists', 'link', 'image', 'table'],
        'toolbar': 'undo redo | styles | bold italic | alignleft aligncenter alignright | bullist numlist',
    },
}

# TinyMCE compressor settings
TINYMCE_COMPRESSOR = False

# TinyMCE spellchecker settings
TINYMCE_SPELLCHECKER = True
TINYMCE_SPELLCHECKER_DEFAULT_LANGUAGE = 'en'




# For development/testing, you can use console backend to see emails in terminal
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Contact form email recipients
CONTACT_EMAIL_RECIPIENTS = ['arfatur.shaikh@gmail.com', 'support@factoryinfohub.com']

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_SECONDS = 31536000
SECURE_REDIRECT_EXEMPT = []
SECURE_SSL_REDIRECT = False  # Set to True in production with HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
X_FRAME_OPTIONS = 'DENY'

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directory exists
import os
os.makedirs(MEDIA_ROOT, exist_ok=True)


# Logging configuration
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')
LOG_FILE = os.environ.get('LOG_FILE', str(BASE_DIR / 'logs/django.log'))

# Ensure logs directory exists
LOG_DIR = os.path.dirname(LOG_FILE)
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_FILE,
            'formatter': 'detailed',
            'maxBytes': 1024*1024*10,  # 10 MB
            'backupCount': 5,
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['mail_admins', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['mail_admins', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'factoryinfohub': {
            'handlers': ['file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'payment_system': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# CSRF_TRUSTED_ORIGINS = ['https://0429-202-134-177-80.ngrok-free.app']

# CSRF_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SECURE = True

# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOWED_ORIGINS = [
#     "https://0429-202-134-177-80.ngrok-free.app",
# ]


# EMAIL_HOST_USER = "arfatur.shaikh@gmail.com"
# EMAIL_HOST_PASSWORD = "lyfq xmir oiul voqe"


# Custom 404 error handler
handler404 = 'django.views.defaults.page_not_found'