# Generated by Django 5.2.6 on 2026-03-19 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Karkahan', '0018_add_payment_completed_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending Too Long'), ('email_not_received', 'Order Email Not Received'), ('duplicate_charge', 'Duplicate Charge'), ('payment_verification', 'Payment Verification Issue'), ('other', 'Other Issue')], max_length=50)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('user_description', models.TextField(blank=True, help_text="User's description of the issue")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser_info', models.CharField(blank=True, max_length=200)),
                ('order_details', models.JSONField(default=dict, help_text='Snapshot of order details at time of report')),
                ('payment_status_at_report', models.CharField(blank=True, max_length=20)),
                ('email_status_at_report', models.CharField(blank=True, max_length=20)),
                ('transaction_id_at_report', models.CharField(blank=True, max_length=255)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for support team')),
                ('resolution_notes', models.TextField(blank=True, help_text='Resolution details')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='Karkahan.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Issue Report',
                'verbose_name_plural': 'Payment Issue Reports',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status'], name='admin_inter_status_536684_idx'), models.Index(fields=['issue_type'], name='admin_inter_issue_t_dedb4f_idx'), models.Index(fields=['priority'], name='admin_inter_priorit_367e9f_idx'), models.Index(fields=['reported_at'], name='admin_inter_reporte_63029d_idx'), models.Index(fields=['user'], name='admin_inter_user_id_a175d1_idx'), models.Index(fields=['order'], name='admin_inter_order_i_6a6871_idx')],
            },
        ),
    ]
